name: NammaYatri Branches

on:
  create:
    branches:
      - 'nammayatri-*'  # Trigger only when the branch name starts with 'nammayatri-'

jobs:
  handle_changes:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/nammayatri-')  # Ensure the job runs only for nammayatri-* branches

    steps:
      - name: Debug Event
        run: |
          echo "Event: ${{ toJson(github.event) }}"
          
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}
      
      - name: Create Pull Request
        run: |
          # Set variables
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          BASE_BRANCH=main
          HEAD_BRANCH=${{ github.event.ref }}
          TITLE="Merge ${HEAD_BRANCH} into ${BASE_BRANCH}"
          BODY="Created by GitHub action"
          TOKEN=${{ secrets.PAT_TOKEN }}
  
          # Create pull request using curl
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/pulls \
            -d "{\"title\":\"$TITLE\",\"body\":\"$BODY\",\"head\":\"${HEAD_BRANCH}\",\"base\":\"${BASE_BRANCH}\"}"
